### ISSUE TITLE
测试用例无法打开 404

### ISSUE THREAD

**Issue by jume2003** [sparrowzoo/sparrow-shell#13]
测试用例无法打开 404，这个算是第一个 issues吧。哈哈

**Comment by sparrowzoo** [comment]
第一步:cd sparrow-bom
第二步:mvn clean install -Dmaven.test.skip
第三步:cd ..
第四步:mvn clean install -Dmaven.test.skip
第五步:sparrow-test 运行tomcat 插件

第六步：浏览器打开浏览器 localhost:7777
<img width="693" alt="企业微信截图_16553431824765" src="https://user-images.githubusercontent.com/5276088/173972467-eec591c0-70d1-4784-ba2f-4c1a30a20780.png">

**Comment by jume2003** [comment]
志哥别误会我说的是项目github首页 
![image](https://user-images.githubusercontent.com/6630946/174300715-b4c5aee1-b8fa-4fee-a602-0c2a06cf4fb9.png)

**Comment by sparrowzoo** [comment]
> 志哥别误会我说的是项目github首页 ![image](https://user-images.githubusercontent.com/6630946/174300715-b4c5aee1-b8fa-4fee-a602-0c2a06cf4fb9.png)

没事 挺好的 也给大家完善了
