### ISSUE TITLE
JSON response should have `content-type` = `application/json` 

### ISSUE THREAD

**Issue by skyline75489** [sparrowzoo/sparrow-shell#20]
https://github.com/sparrowzoo/sparrow-shell/blob/aeafb5afe77b4c5316915ce61b8bf1e40aeff4de/sparrow-test/src/main/java/com.sparrow/controller/HelloController.java#L69

This now returns `text/html` which is not expected.

**Comment by sparrowzoo** [comment]
![image](https://user-images.githubusercontent.com/5276088/178170994-425b9018-5494-497e-8070-f1ba055b49f9.png)
auto support content-type = application/json

https://github.com/sparrowzoo/sparrow-shell/blob/master/sparrow-mvc/src/main/java/com/sparrow/mvc/result/impl/JsonMethodReturnValueResolverHandlerImpl.java

**Comment by skyline75489** [comment]
Interesting. I see different result:

http://www.sparrowzoo.com/json-test.json

![image](https://user-images.githubusercontent.com/4710575/178182771-a71ab271-650b-4a1f-a146-69554af64267.png)

**Comment by skyline75489** [comment]
Full payload:

![image](https://user-images.githubusercontent.com/4710575/178182937-fd4e4fdb-2ab2-49fe-b8d6-be8596e7a6b8.png)

**Comment by sparrowzoo** [comment]
DONE

**Comment by sparrowzoo** [comment]
done
