### ISSUE TITLE
Support `@RequestMapping` annotation alongside XML configuration

### ISSUE THREAD

**Issue by skyline75489** [sparrowzoo/sparrow-shell#21]
https://github.com/sparrowzoo/sparrow-shell/blob/aeafb5afe77b4c5316915ce61b8bf1e40aeff4de/sparrow-test/src/main/resources/controller.xml#L16

It's not easy to maintain XML configuration for request mappings. `@RequestMapping` in Spring is a more intuitive way.

**Comment by sparrowzoo** [comment]
Spring MVC注释暂没有标准的annotation注解，为减少自定义注解入浸代码，目前sparrow 暂未支持,
目前暂支持参数注解
```
 @RequestParameters("threadId,pageIndex")
```
RequestMapping 后续可以考虑引入。

**Comment by sparrowzoo** [comment]
```
   <dependency>
                <groupId>javax.inject</groupId>
                <artifactId>javax.inject</artifactId>
                <version>1</version>
            </dependency>
```
jdk javax.inject support
