### ISSUE TITLE
Support Java 11 and above

### ISSUE THREAD

**Issue by skyline75489** [sparrowzoo/sparrow-shell#22]
https://github.com/sparrowzoo/sparrow-shell/blob/aeafb5afe77b4c5316915ce61b8bf1e40aeff4de/sparrow-test/src/test/java/com/sparrow/facade/unzip/GZipUtil.java#L23

The class `sun.misc.BASE64Decoder` is no longer available in Java 11+

**Comment by sparrowzoo** [comment]
this is test demo 
sparrow core support jdk 8
sun.misc.BASE64Decoder not exist in sparrow core framework
