### ISSUE TITLE
sparrow-orm should not assume MySQL as the database

### ISSUE THREAD

**Issue by skyline75489** [sparrowzoo/sparrow-shell#23]
https://github.com/sparrowzoo/sparrow-shell/blob/aeafb5afe77b4c5316915ce61b8bf1e40aeff4de/sparrow-orm/src/main/java/com/sparrow/orm/AbstractEntityManagerAdapter.java#L167

It should work with other databases like SQLite.

**Comment by sparrowzoo** [comment]
this is only support for mysql code generator
sparrow support SQL Dialect 
```
 public enum Dialect {
    MYSQL,
    SQL_SERVER,
    ELASTIC_SEARCH
}
```

这段代码是数据表创建SQL 只用于mysql 代码生成器（还未开源）
其他的 INSERT DELETE UPDATE SELECT 等常用SQL是支持SQL方言的，代码生成部分后续可以提供支持
