### ISSUE TITLE
The check-style config with a wrong regex make the mvn Install fail

### ISSUE THREAD

**Issue by bigduu** [sparrowzoo/sparrow-shell#39]
As below pic 
![image](https://user-images.githubusercontent.com/18681616/192580428-38dcb7d6-6610-4a7e-a822-7971b99230ea.png)

please help make this line correct `style/sparrow_checkstyle.xml:32`
![image](https://user-images.githubusercontent.com/18681616/192580646-9c1c4ad4-40ba-44e4-9d3d-dfeac9ce1e3f.png)

**Comment by sparrowzoo** [comment]
fixed
